### ISSUE TITLE
Option to un-subscribe a feed

### ISSUE THREAD

**Issue by rickdtc** [niilopoutanen/rss-feed#46]
It would be great of the option to unsunscribe to a feed was added

also just wanna say this is a very underrated app, thanks for all this work and keeping it straight forward with the experience, love it

**Comment by niilopoutanen** [comment]
Thanks for the feedback! 
You can remove a source by swiping it left in the "sources"-tab, if that's what you mean.

**Comment by rickdtc** [comment]
That is exactly what I meant, thanks for your time, will play around with the app more before making some features requests that I thought of

Also on a side note can that red be turned softer so that it goes a little easier on the eyes, thanks

![Screenshot_20240605_211048_RSS-Feed](https://github.com/niilopoutanen/rss-feed/assets/74096544/5e149cb3-f0f7-49ad-833c-d2122cbf3d73)
